/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Viws;

import Funcionarios.Funcionario;
import Hospedes.Hospede;
import Reservas.Reserva;
import data.HospedeReservaDAO;
import data.ReservaDAO;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.table.DefaultTableModel;


/**classe que contem tela inicial do programa
 *
 * @author Daniel
 */
public class TelaInicial extends javax.swing.JFrame {
    
    private final String[] tableColumns = {"Id", "Data da Reserva", "Entrada", "Saída","Número de Hospede", "Número do Quarto", "Orçamento", "Pagamento Realizado?"};
 
    DefaultTableModel tableModel = new DefaultTableModel(tableColumns, 0);
    
    private ReservaDAO reservaDAO = new ReservaDAO();
    private HospedeReservaDAO hospedeReservaDAO = new HospedeReservaDAO();

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        setLocationRelativeTo(null);
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        lblImagem = new javax.swing.JLabel();
        lblReservas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();
        mbMenu = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        mnReserva = new javax.swing.JMenu();
        mniRealizaReserva = new javax.swing.JMenuItem();
        mniCheckInCheckOut = new javax.swing.JMenuItem();
        mnCadastrar = new javax.swing.JMenu();
        mniCadastroHospede = new javax.swing.JMenuItem();
        mniCadastroFuncionario = new javax.swing.JMenuItem();
        mniCadastroQuarto = new javax.swing.JMenuItem();
        mnVisualizar = new javax.swing.JMenu();
        mniVisualisarReservas = new javax.swing.JMenuItem();
        mniVisualizarHospedes = new javax.swing.JMenuItem();
        mniVisualizarFuncionarios = new javax.swing.JMenuItem();
        mniVisualizarQuartos = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Inicial");

        jPanel1.setToolTipText("tela inicial");

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final.png"))); // NOI18N
        lblImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblReservas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblReservas.setText("Reservas do dia:");

        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Data da Reserva", "Entrada", "Saída", "Número de Hospedes", "Número do Quarto", "Orçamento", "Pagamento Realizado?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReservas.setToolTipText("dados das reservas ");
        jScrollPane1.setViewportView(tblReservas);
        tblReservas.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 830, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReservas)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblImagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReservas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menu.setText("          MENU           ");
        menu.setMinimumSize(new java.awt.Dimension(60, 22));

        mnReserva.setText("    Reserva     ");

        mniRealizaReserva.setText("   Realizar reserva");
        mniRealizaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRealizaReservaActionPerformed(evt);
            }
        });
        mnReserva.add(mniRealizaReserva);

        mniCheckInCheckOut.setText("Check-In/Check-Out");
        mniCheckInCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCheckInCheckOutActionPerformed(evt);
            }
        });
        mnReserva.add(mniCheckInCheckOut);

        menu.add(mnReserva);

        mnCadastrar.setText("    Cadastrar");

        mniCadastroHospede.setText("Cadastrar Hospede");
        mniCadastroHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadastroHospedeActionPerformed(evt);
            }
        });
        mnCadastrar.add(mniCadastroHospede);

        mniCadastroFuncionario.setText("Cadastrar Funcionario");
        mniCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadastroFuncionarioActionPerformed(evt);
            }
        });
        mnCadastrar.add(mniCadastroFuncionario);

        mniCadastroQuarto.setText("Cadastrar Quarto");
        mniCadastroQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadastroQuartoActionPerformed(evt);
            }
        });
        mnCadastrar.add(mniCadastroQuarto);

        menu.add(mnCadastrar);

        mnVisualizar.setText("    Visualizar");

        mniVisualisarReservas.setText("Visualizar Reservas");
        mniVisualisarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVisualisarReservasActionPerformed(evt);
            }
        });
        mnVisualizar.add(mniVisualisarReservas);

        mniVisualizarHospedes.setText("Visualizar Hospedes");
        mniVisualizarHospedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVisualizarHospedesActionPerformed(evt);
            }
        });
        mnVisualizar.add(mniVisualizarHospedes);

        mniVisualizarFuncionarios.setText("Visualizar Funcionarios");
        mniVisualizarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVisualizarFuncionariosActionPerformed(evt);
            }
        });
        mnVisualizar.add(mniVisualizarFuncionarios);

        mniVisualizarQuartos.setText("Visualizar Quartos");
        mniVisualizarQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVisualizarQuartosActionPerformed(evt);
            }
        });
        mnVisualizar.add(mniVisualizarQuartos);

        menu.add(mnVisualizar);

        mbMenu.add(menu);

        setJMenuBar(mbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**começa uma nova reserva
     * 
     * @param evt 
     */
    private void mniRealizaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRealizaReservaActionPerformed
       
        TelaReservaData telaReservaData = new TelaReservaData();
        
        telaReservaData.setVisible(true);
        
    }//GEN-LAST:event_mniRealizaReservaActionPerformed

    
    /**abre tela para selecionar reserva para check-in e check-out
     * 
     * @param evt 
     */
    private void mniCheckInCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCheckInCheckOutActionPerformed
        
        TelaSelecaoReserva telaSelecaoReserva = new TelaSelecaoReserva();
        
        telaSelecaoReserva.atualizarTabela();
        
        telaSelecaoReserva.setVisible(true);
        
    }//GEN-LAST:event_mniCheckInCheckOutActionPerformed

    
    
    
    /**abre tela para cadastro de hospede
     * 
     * @param evt 
     */
    private void mniCadastroHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadastroHospedeActionPerformed
       
        TelaCadastroHospede telaCadastroHospede = new TelaCadastroHospede();
       
        telaCadastroHospede.setVisible(true);
        
    }//GEN-LAST:event_mniCadastroHospedeActionPerformed

    
    /**abre tela para cadastro de funcionario
     * 
     * @param evt 
     */
    private void mniCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadastroFuncionarioActionPerformed
       
        TelaCadastroFuncionarios telaCadastroFuncionario = new TelaCadastroFuncionarios();
        
        telaCadastroFuncionario.setVisible(true);
        
    }//GEN-LAST:event_mniCadastroFuncionarioActionPerformed

    
    /**abre tela para cadastro de quarto
     * 
     * @param evt 
     */
    private void mniCadastroQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadastroQuartoActionPerformed
        
        TelaCadastroQuarto telaCadastroQuarto = new TelaCadastroQuarto();
        
        telaCadastroQuarto.setVisible(true);
        
    }//GEN-LAST:event_mniCadastroQuartoActionPerformed

    
    /**abre tela para a visualização das reservas
     * 
     * @param evt 
     */
    private void mniVisualisarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVisualisarReservasActionPerformed
        
        TelaReservas telaReservas = new TelaReservas();
        
        telaReservas.atualizarTabela();
        
        telaReservas.setVisible(true);
        
    }//GEN-LAST:event_mniVisualisarReservasActionPerformed

    
    /**abre tela para visualização dos Hospedes
     * 
     * @param evt 
     */
    private void mniVisualizarHospedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVisualizarHospedesActionPerformed
        
        TelaHospedes telaHospedes = new TelaHospedes();
        
        telaHospedes.atualizarTabela();
        
        telaHospedes.setVisible(true);
        
    }//GEN-LAST:event_mniVisualizarHospedesActionPerformed

    
    /**abre tela para a visualização dos Funcionarios
     * 
     * @param evt 
     */
    private void mniVisualizarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVisualizarFuncionariosActionPerformed
       
        TelaFuncionarios telaFuncionarios = new TelaFuncionarios();
       
        telaFuncionarios.atualizarTabela();
        
        telaFuncionarios.setVisible(true);
        
    }//GEN-LAST:event_mniVisualizarFuncionariosActionPerformed

    
    /**abre tela para a visualização dos quartos
     * 
     * @param evt 
     */
    private void mniVisualizarQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVisualizarQuartosActionPerformed
        
        TelaQuartos telaQuartos = new  TelaQuartos();
        
        telaQuartos.atualizarTabela();
        
        telaQuartos.setVisible(true);
        
    }//GEN-LAST:event_mniVisualizarQuartosActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblReservas;
    private javax.swing.JMenuBar mbMenu;
    private javax.swing.JMenu menu;
    private javax.swing.JMenu mnCadastrar;
    private javax.swing.JMenu mnReserva;
    private javax.swing.JMenu mnVisualizar;
    private javax.swing.JMenuItem mniCadastroFuncionario;
    private javax.swing.JMenuItem mniCadastroHospede;
    private javax.swing.JMenuItem mniCadastroQuarto;
    private javax.swing.JMenuItem mniCheckInCheckOut;
    private javax.swing.JMenuItem mniRealizaReserva;
    private javax.swing.JMenuItem mniVisualisarReservas;
    private javax.swing.JMenuItem mniVisualizarFuncionarios;
    private javax.swing.JMenuItem mniVisualizarHospedes;
    private javax.swing.JMenuItem mniVisualizarQuartos;
    private javax.swing.JTable tblReservas;
    // End of variables declaration//GEN-END:variables



    /**atualiza tabela com os dados das reservas cadastradas
     * 
     */
    public void atualizarTabela(){
        
        List<Reserva> reservas = reservaDAO.listarReservas();
        
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy"); 
     
         if(!reservas.isEmpty()){
      
            tableModel = new DefaultTableModel(tableColumns, 0);
      
            for (Reserva r : reservas) {
                
                List<Hospede> hospedes = hospedeReservaDAO.hospedesReserva(r);
                
                String dataReserva = String.valueOf(formato.format(r.getDataReserva()));
                String dataEntrada = String.valueOf(formato.format(r.getDataEntrada()));
                String dataSaida = String.valueOf(formato.format(r.getDataSaida()));
     
                Object[] rowData = {r.getId(), dataReserva, dataEntrada, dataSaida, hospedes.size(),
                    r.getQuarto().getNumero(), r.getOrcamento().getValorFinal(), r.getOrcamento().getPagamentoRealizado()};
             
                tableModel.addRow(rowData);
      
                tblReservas.setModel(tableModel);
     
            }
        }
    }
    
    
    public void validaUsuario(Funcionario usuario) {
        
        if( usuario.getDepartamento().getNome().equalsIgnoreCase("Gerencia") ) {
            
         } 
        else if ( usuario.getDepartamento().getNome().equalsIgnoreCase("Financeiro") ) {
            
            mniCadastroFuncionario.setEnabled(true);
            mniCadastroFuncionario.setVisible(false);
            
        }
        else if ( usuario.getDepartamento().getNome().equalsIgnoreCase("Atendente") ) {
            
            mniCadastroFuncionario.setEnabled(true);
            mniCadastroFuncionario.setVisible(false);
            
            mniCadastroQuarto.setEnabled(true);
            mniCadastroQuarto.setVisible(false);
            
            mniVisualizarFuncionarios.setEnabled(true);
            mniVisualizarFuncionarios.setVisible(false);
            
        } 
    }

}
