/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Viws;

import Hospedes.Hospede;
import Reservas.Reserva;
import data.HospedeReservaDAO;
import data.ReservaDAO;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**classe que contem tela para selecionar uma reserva
 *
 * @author Daniel
 */
public class TelaSelecaoReserva extends javax.swing.JFrame {
    
    
    private final String[] tableColumns = {"Id", "Data da Reserva", "Entrada", "Saída","Número de Hospede", "Número do Quarto", "Orçamento", "Pagamento Realizado?"};
 
    DefaultTableModel tableModel = new DefaultTableModel(tableColumns, 0);
    
    private ReservaDAO reservaDAO = new ReservaDAO();
    private HospedeReservaDAO hospedeReservaDAO = new HospedeReservaDAO();

    /**
     * Creates new form TelaSelecaoReserva
     */
    public TelaSelecaoReserva() {
        initComponents();
        setLocationRelativeTo(null);
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSelecioneReserva = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();
        btnCheckOut = new javax.swing.JButton();
        btnCheckIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecionar Reserva");

        jPanel1.setToolTipText("selecione uma reserva");

        lblSelecioneReserva.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSelecioneReserva.setText("Selecione uma Reserva:");

        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Data da Reserva", "Entrada", "Saída", "Número de Hospedes", "Número do Quarto", "Orçamento", "Pagamento Realizado?", "Title 8"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblReservas);

        btnCheckOut.setText("Realizar Check-Out");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        btnCheckIn.setText("Realizar Check-In");
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSelecioneReserva)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCheckIn)
                        .addGap(18, 18, 18)
                        .addComponent(btnCheckOut))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblSelecioneReserva)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**botão para abrir a tela de check-out com a reserva selecionada
     * 
     * @param evt 
     */
    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        
            Reserva reserva = null;
        
            try {
                
                int id = (int) tblReservas.getValueAt(tblReservas.getSelectedRow(), 0);
        
                reserva = reservaDAO.reservaPorId(id);
                
                if (reserva.getCheckOut()) {
                    
                    JOptionPane.showMessageDialog(rootPane, "Check-Out já realizado nesta reserva");
                    
                } else if (!reserva.getCheckIn()) {
                    
                    JOptionPane.showMessageDialog(rootPane, "Check-In ainda não realizado");
                    
                } else {
                
                TelaCheckOut telaCheckOut = new TelaCheckOut();
            
                telaCheckOut.setReserva(reserva);
                telaCheckOut.preencheCampo();
            
                telaCheckOut.setVisible(true);
                
                }
        
            } catch (IndexOutOfBoundsException e) {
            
                JOptionPane.showMessageDialog(rootPane, "Selecione uma Reserva");
            
            }

    }//GEN-LAST:event_btnCheckOutActionPerformed

    
    /**botão para abrir a tela de check-in com a reserva selecionada
     * 
     * @param evt 
     */
    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
       
            Reserva reserva = null;
        
            try {
        
                int id =  (int) tblReservas.getValueAt(tblReservas.getSelectedRow(), 0);
        
                reserva = reservaDAO.reservaPorId(id);
                
                if (reserva.getCheckIn()) {
                    
                    JOptionPane.showMessageDialog(rootPane, "Check-In já realizado nesta reserva");
                    
                } else {
                
                    TelaCheckIn telaCheckIn = new TelaCheckIn();
            
                    telaCheckIn.setReserva(reserva);
                    
                    telaCheckIn.setVisible(true);
                    
                }
        
             } catch (IndexOutOfBoundsException e) {
            
                JOptionPane.showMessageDialog(rootPane, "Selecione uma Reserva");
            
            }
        
    }//GEN-LAST:event_btnCheckInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSelecaoReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSelecaoReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSelecaoReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSelecaoReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSelecaoReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSelecioneReserva;
    private javax.swing.JTable tblReservas;
    // End of variables declaration//GEN-END:variables



/**atualiza tabela com os dados das reservas cadastradas
 * 
 */
    public void atualizarTabela(){
        
        List<Reserva> reservas = reservaDAO.listarReservas();
        
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy"); 
     
         if(!reservas.isEmpty()){
      
            tableModel = new DefaultTableModel(tableColumns, 0);
      
            for (Reserva r : reservas) {
                
                List<Hospede> hospedes = hospedeReservaDAO.hospedesReserva(r);
                
                String dataReserva = String.valueOf(formato.format(r.getDataReserva()));
                String dataEntrada = String.valueOf(formato.format(r.getDataEntrada()));
                String dataSaida = String.valueOf(formato.format(r.getDataSaida()));
     
                Object[] rowData = {r.getId(), dataReserva, dataEntrada, dataSaida, hospedes.size(),
                    r.getQuarto().getNumero(), r.getOrcamento().getValorFinal(), r.getOrcamento().getPagamentoRealizado()};
             
                tableModel.addRow(rowData);
      
                tblReservas.setModel(tableModel);
     
            }
        }
         
    }
   
}
