/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Viws;


import Quartos.Quarto;
import Reservas.Reserva;
import data.QuartoDAO;
import data.ReservaDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**classe que contem tela para selecionar quarto para a reserva
 *
 * @author Daniel
 */
public class TelaReservaQuarto extends javax.swing.JFrame {
    
    private final String[] tableColumns = {"Número Quarto", "Descrição", "Capacidade","Valor Diaria"};
 
    DefaultTableModel tableModel = new DefaultTableModel(tableColumns, 0);
 
    private Reserva reserva;
    
    private QuartoDAO quartoDAO = new QuartoDAO();
    
    private List<Quarto>  quartos = new QuartoDAO().listarQuartos();

    /**
     * Creates new form TelaReservaQuarto
     */
    public TelaReservaQuarto() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

   
     /**setter
      * 
      * @param reserva 
      */
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblQuartosDisponiveis = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQuartos = new javax.swing.JTable();
        lblSelecione = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quartos Reserva");

        jPanel1.setToolTipText("selecione um quarto para a reserva");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Realizando Reserva");

        lblQuartosDisponiveis.setText("Quartos disponíveis para a data:");

        tblQuartos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Número Quarto", "Descrição", "Capacidade", "Valor Diaria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblQuartos);

        lblSelecione.setText("Selecione um dos quartos da tabela");

        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(lblTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQuartosDisponiveis)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblSelecione)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnContinuar))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTitulo)
                .addGap(37, 37, 37)
                .addComponent(lblQuartosDisponiveis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSelecione))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnContinuar)))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**botão para avançar para a proxima etapa da reserva
     * 
     * @param evt 
     */
    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed

        try {
            
            String numero = (String) tblQuartos.getValueAt(tblQuartos.getSelectedRow(), 0);
            
            reserva.setQuarto(quartoDAO.quartoPorNumero(Integer.parseInt(numero)));
            
            JOptionPane.showMessageDialog(rootPane, "Quarto adicionado");
            
            
            TelaReservaHospede telaReservaHospede = new TelaReservaHospede();
        
            telaReservaHospede.setReserva(reserva);
        
            telaReservaHospede.setVisible(true);
        
            this.dispose();
        
             } catch (IndexOutOfBoundsException e) {
            
            JOptionPane.showMessageDialog(rootPane, "Selecione um quarto");
            
        }
    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaReservaQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaReservaQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaReservaQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaReservaQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaReservaQuarto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblQuartosDisponiveis;
    private javax.swing.JLabel lblSelecione;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblQuartos;
    // End of variables declaration//GEN-END:variables




    
/**atualiza tabela com os dados dos quartos cadastrados
 * 
 */
public void atualizarTabela(){
    
     if(!quartos.isEmpty()){
      
         tableModel = new DefaultTableModel(tableColumns, 0);
         
         ReservaDAO reservaDAO = new ReservaDAO();
      
         for (Quarto q : quartos) {
             
             if (reservaDAO.validaQuartoR(reserva.getDataEntrada(), reserva.getDataSaida(), q)) {
             
             }
             
             else if (!reservaDAO.validaQuartoR(reserva.getDataEntrada(), reserva.getDataSaida(), q)) {
                 
                 String numero = String.valueOf(q.getNumero());
                 String capacidade = String.valueOf(q.getTipoQuarto().getCapacidade());
                 String valor = String.valueOf(q.getTipoQuarto().getValorDiaria());
          
                 Object[] rowData = {numero, q.getTipoQuarto().getDescricao(), capacidade, "R$ " + valor};
           
                 tableModel.addRow(rowData);
                 
             }
         }
      
         tblQuartos.setModel(tableModel);
         
     }else{
       
         tableModel = new DefaultTableModel(tableColumns, 0);
         tblQuartos.setModel(tableModel);
         
     }     
  }
    

/**retorna posição do quarto selecionado
 * 
 * @return 
 */
 private int getPosicaoQuarto(){
    
     int posQuarto = tblQuartos.getSelectedRow();
    
     return posQuarto;
  }
      
      
/**retorna quarto selecionado
 * 
 * @return 
 */
      private Quarto getQuarto() {
          
          Quarto quarto = quartos.get(getPosicaoQuarto());
            
        return quarto;
        
      }

}
