/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Viws;

import Hospedes.Hospede;
import Reservas.Reserva;
import data.HospedeReservaDAO;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**classe que contem tela com todos os dados da reserva
 *
 * @author Daniel
 */
public class TelaReservaDados extends javax.swing.JFrame {
    
    private final String[] tableColumns = {"CPF", "Nome", "Nascimento","Gênero", "RG", "Telefone", "Endereço", "Observações"};
 
    DefaultTableModel tableModel = new DefaultTableModel(tableColumns, 0);
    
    private Reserva reserva;
    
    
    
    HospedeReservaDAO hospedeReservaDAO = new HospedeReservaDAO();
    
    
    
    /**
     * Creates new form TelaReservaDados
     */
    public TelaReservaDados() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    
    /**setter
     * 
     * @param reserva 
     */
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }

    
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblDados = new javax.swing.JLabel();
        lblDataReserva = new javax.swing.JLabel();
        lblDataEntrada = new javax.swing.JLabel();
        lblDataSaida = new javax.swing.JLabel();
        lblNumeroHospedes = new javax.swing.JLabel();
        lblNumeroQuarto = new javax.swing.JLabel();
        lblOrcamento = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHospedes = new javax.swing.JTable();
        btnFinalizar = new javax.swing.JButton();
        lblCheckIn = new javax.swing.JLabel();
        lblCheckOut = new javax.swing.JLabel();
        lblPagamento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dados reserva");

        jPanel1.setToolTipText("dados da reserva");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Realizando Reserva");

        lblDados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDados.setText("Dados da Reserva:");

        lblDataReserva.setText("Data da reserva:");

        lblDataEntrada.setText("Entrada:");

        lblDataSaida.setText("Saída:");

        lblNumeroHospedes.setText("Número de hospedes:");

        lblNumeroQuarto.setText("Número do quarto:");

        lblOrcamento.setText("Orçamento:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Hospedes:");

        tblHospedes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Nascimento", "Gênero", "RG", "Telefone", "Endereço", "Observações"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblHospedes.setToolTipText("dados dos hospedes da reserva");
        jScrollPane1.setViewportView(tblHospedes);

        btnFinalizar.setText("Finalizar Reserva");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        lblCheckIn.setText("Check-in Realizado?:");

        lblCheckOut.setText("Check-out Realizado?:");

        lblPagamento.setText("Pagamneto Realizado?:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(lblTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDados)
                            .addComponent(lblDataReserva)
                            .addComponent(lblDataEntrada)
                            .addComponent(lblDataSaida)
                            .addComponent(lblNumeroHospedes)
                            .addComponent(lblNumeroQuarto)
                            .addComponent(lblOrcamento)
                            .addComponent(jLabel1)
                            .addComponent(lblCheckIn)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblPagamento)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnFinalizar))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCheckOut))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblDados)
                .addGap(18, 18, 18)
                .addComponent(lblDataReserva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDataEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDataSaida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumeroHospedes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumeroQuarto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOrcamento)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCheckIn)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblCheckOut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPagamento)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );

        jLabel1.getAccessibleContext().setAccessibleParent(tblHospedes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**botão para finalizar a reserva
     * 
     * @param evt 
     */
    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_btnFinalizarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaReservaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaReservaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaReservaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaReservaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaReservaDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCheckIn;
    private javax.swing.JLabel lblCheckOut;
    private javax.swing.JLabel lblDados;
    private javax.swing.JLabel lblDataEntrada;
    private javax.swing.JLabel lblDataReserva;
    private javax.swing.JLabel lblDataSaida;
    private javax.swing.JLabel lblNumeroHospedes;
    private javax.swing.JLabel lblNumeroQuarto;
    private javax.swing.JLabel lblOrcamento;
    private javax.swing.JLabel lblPagamento;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblHospedes;
    // End of variables declaration//GEN-END:variables


    
    /**atualiza a tabela com dados dos hospedes da reserva
     * 
     */
    public void atualizarTabela(){
        
            List<Hospede> hospedes = hospedeReservaDAO.hospedesReserva(reserva);
     
//         if(!reserva.getHospedes().isEmpty()){
      
            tableModel = new DefaultTableModel(tableColumns, 0);
            
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy"); 
      
            for (Hospede h : hospedes) {
                
                String rg = String.valueOf( h.getRg());
                String telefone = String.valueOf( h.getTelefone());
                String data = String.valueOf(formato.format(h.getNascimento()));
     
                String[] rowData = {h.getCpf(), h.getNome(), data, h.getGenero(), rg,
                    telefone, h.getEndereco(), h.getObservacoes()};
             
                tableModel.addRow(rowData);
      
                tblHospedes.setModel(tableModel);
     
            
        }
         
    }
    
    
    /**atualiza todos os dados da reserva
     * 
     */
    public void AtualizaDados() {
        
        List<Hospede> hospedes = hospedeReservaDAO.hospedesReserva(reserva);
        
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy"); 
        
        String dataReserva = String.valueOf(formato.format(reserva.getDataReserva()));
        String dataEntrada = String.valueOf(formato.format(reserva.getDataEntrada()));
        String dataSaida = String.valueOf(formato.format(reserva.getDataSaida()));
        
        lblDataReserva.setText("Data da reserva: " + dataReserva);
        lblDataEntrada.setText("Entrada: " + dataEntrada);
        lblDataSaida.setText("Saída: " + dataSaida);
        lblNumeroHospedes.setText("Número de hospedes: " + hospedes.size());
        lblNumeroQuarto.setText("Número do quarto: " + reserva.getQuarto().getNumero());
        lblOrcamento.setText("Orçamento: R$ " + reserva.getOrcamento().getValorFinal());
        
        if (reserva.getCheckIn()) {
            
             lblCheckIn.setText("Check-in Realizado?: Sim");
            
        } else {
            
             lblCheckIn.setText("Check-in Realizado?: Não");
            
        }
        
        if (reserva.getCheckOut()) {
            
            lblCheckOut.setText("Check-out Realizado?: Sim");
            
        } else {
            
            lblCheckOut.setText("Check-out Realizado?: Não");
            
        }
        
        if (reserva.getOrcamento().getPagamentoRealizado()) {
            
            lblPagamento.setText("Pagamneto Realizado?: Sim");
            
        } else {
            
            lblPagamento.setText("Pagamneto Realizado?: Não");
            
        }
    }

}
